# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

# Gatilho: Este workflow roda toda vez que houver um push na branch 'main'
on:
  push:
    branches: [ "master" ]
  
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# Permissões necessárias para o workflow interagir com seu repositório
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4